language: java
sudo: false
jdk:
- oraclejdk8
install: true
script: "./buildtravis.sh"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2"
env:
  global:
  - secure: "CsWhmBYtAXuHz0DNsH7tFGaBgn3On9wHwXliuGb6Opjmle0BbVAPsl3WBIF0MCGuLyIzyunjoMlIoz8LFq6EoVzxH2BW2+GKKqP+Gvak8h8sd3v6G/CQQP/Al+3cZ7mphYGyYiAbNO4nV8ZE/imoV9QRtoEYcMcrGN7C3YH15DFu3xQfpzZjZO1AKITWeOqf8c5AgsGVDfldtAbgTlGIPAslAxfPZNL4v+FWTJs81IbQwwo32gxhKJC14E2LgpCrcCdgqLzU8780oRJGbkGjXmTLRtGgdCV4eGa/Ct5Q5oH90VlTCZRGCe4JQepMJpfXRIeBqKuNN8cXGEk6i7TYWR9TofSvFJome0Xaq/TKucJ2Ggusg79B+dXefoB3sg7MaPiLD33S7qznv28m/rH1OB5v9l3yRQllU0fcx2mVxcGEYkwMjQUU38gKnUx7DUl5rdnKU5imTzrx6GU3MeH9rpHIiY8ji0WYeHGCPIsavpfqYpkc7U7oDodXnJZJSdInnQUwOb68iwLJKePx+sjHMLtpnI9L77o0rShUAi1xg4TVrnoR7z2oD40dG1qOQS2Z1nieZVwAeoGFC+JyzqL2FVGU9HxXnwteHozahni/rapuqLWtaTx91KcPveiL62zU8Y8qskFQuacDTIiwcfld7hPOp8u9uNu3DFYoH/7b1n8="
  - secure: "XrcvODTAqH7y+ZON9cjuAbFe11mgTGKJhceXeuAuepPQCefC1EHQ4U2VYr4z4Lb6m9mUaw8E67+w64bE6bVpc0KFkDaxZU0XF8FBcNO3+rUpbDtQGS9kTq3lpTTid9jamv3HzaoDDVUfzAeCwG44LfCQJvmjnRrHjuZOUlTJCXTEarnwGFUtRlTXtnERTduxXNX9GwrOUKxI7XCA/ZTgIDSthusOqP6/6QiPYQNPgq8XB3ImGAC2CAZjO6S6Lh5owVLX96s8MZ0Zoc3qfSHXUM9z4kLJMfO4fRrbZsnco6Dq5g+362OWY7buq6MA2MBR0sxOApUuHkm+I5hQRJgiIUgxnlaky//47xMwUwSKDFgWLm2+Yes+as5XVMFi09cB5OFsRM4YBkqCDyioN5mCM/TSvlKLF86tClhyOYk/Jmyl6Go3VESounfGFoRQYFGAcxb2FIT3PKOkUucNxBeSzSrx0jYXf+RSbpEYAD2PeYITmenV88z/TZ48FYG21ZrD1SVXgfI6beWIa3wSgGWlyrT816wuh+gYKgRKaGjxC27XShxrKaUU4BMtpygxbFcPj3Xn5rZXG0929Y7eeJTkExxI2MSR8oixYvurOdUCgh5tvweO82DSPp1+aBCh5hU2PWS5G3H2aOnN55iHr1ZKwed1HbyteyfufCmaxqAcIkg="
